/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/address-book-api';
export * from './apis/address-book-legacy-api';
export * from './apis/cors-api';
export * from './apis/group-api';
export * from './apis/login-api';
export * from './apis/peer-api';
export * from './apis/software-api';
export * from './apis/todo-api';
export * from './apis/user-api';
export * from './apis/webconsole-api';

