/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddUserRequest } from '../models';
import { CurrentUserRequest } from '../models';
import { CurrentUserResponse } from '../models';
import { EnableUserRequest } from '../models';
import { UpdateUserRequest } from '../models';
import { UserList } from '../models';
import { UsersResponse } from '../models';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This function is an API endpoint that allows an authenticated user to retrieve their current user information. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `request`: The request data, which includes the current user information.  <br>  ## Returns  If successful, this function returns a `Json<CurrentUserResponse>` object, which includes the current user information.  <br> If the user is not authorized, this function returns a `status::Unauthorized` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if the user is not authorized.
         * @summary Get the Current User
         * @param {CurrentUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUser: async (body: CurrentUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling currentUser.');
            }
            const localVarPath = `/api/currentUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that adds a new user.  ## Parameters  - `request`: A JSON object containing the new user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Add user
         * @param {AddUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAdd: async (body: AddUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userAdd.');
            }
            const localVarPath = `/api/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that enables or disables users.  ## Parameters  - `request`: A JSON object containing the list of users to enable or disable.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Enable users
         * @param {EnableUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnable: async (body: EnableUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userEnable.');
            }
            const localVarPath = `/api/enable-users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that updates a user.<br> Normal user can only update themselves, admin can update any user.<br>  ## Parameters  - `request`: A JSON object containing the updated user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Update user
         * @param {UpdateUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUpdate: async (body: UpdateUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userUpdate.');
            }
            const localVarPath = `/api/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that allows an authenticated admin to retrieve a paginated list of users. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `current`: The current page number.  - `pageSize`: The number of users per page.  - `email`: The email to filter the users by.  - `name`: The name to filter the users by.  ## Returns  If successful, this function returns a `Json<UserList>` object, which includes a success message, the total number of users, and the list of users.  <br> If no users are found, this function returns a `status::NotFound` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if no users are found.  # Example  GET /api/user-list?current=1&pageSize=10&email=test@test.com&name=Test
         * @summary Get the List of Users
         * @param {number} current 
         * @param {number} page_size 
         * @param {string} [email] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        users: async (current: number, page_size: number, email?: string, name?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'current' is not null or undefined
            if (current === null || current === undefined) {
                throw new RequiredError('current','Required parameter current was null or undefined when calling users.');
            }
            // verify required parameter 'page_size' is not null or undefined
            if (page_size === null || page_size === undefined) {
                throw new RequiredError('page_size','Required parameter page_size was null or undefined when calling users.');
            }
            const localVarPath = `/api/user-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (current !== undefined) {
                localVarQueryParameter['current'] = current;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that retrieves all users.  ## Parameters  - `current`: The current page number for pagination. This parameter is currently unused.  - `pageSize`: The number of items per page for pagination. This parameter is currently unused.  - `accessible`: A boolean value indicating whether the user is accessible. This parameter is currently unused.  - `status`: The status of the user. This parameter is currently unused.  ## Returns  If successful, this function returns a `Json<UserList>` object containing the users.
         * @summary Get Users for client
         * @param {number} current 
         * @param {number} page_size 
         * @param {boolean} [accessible] 
         * @param {number} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersClient: async (current: number, page_size: number, accessible?: boolean, status?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'current' is not null or undefined
            if (current === null || current === undefined) {
                throw new RequiredError('current','Required parameter current was null or undefined when calling usersClient.');
            }
            // verify required parameter 'page_size' is not null or undefined
            if (page_size === null || page_size === undefined) {
                throw new RequiredError('page_size','Required parameter page_size was null or undefined when calling usersClient.');
            }
            const localVarPath = `/api/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (current !== undefined) {
                localVarQueryParameter['current'] = current;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (accessible !== undefined) {
                localVarQueryParameter['accessible'] = accessible;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This function is an API endpoint that allows an authenticated user to retrieve their current user information. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `request`: The request data, which includes the current user information.  <br>  ## Returns  If successful, this function returns a `Json<CurrentUserResponse>` object, which includes the current user information.  <br> If the user is not authorized, this function returns a `status::Unauthorized` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if the user is not authorized.
         * @summary Get the Current User
         * @param {CurrentUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUser(body: CurrentUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CurrentUserResponse>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).currentUser(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that adds a new user.  ## Parameters  - `request`: A JSON object containing the new user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Add user
         * @param {AddUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAdd(body: AddUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UsersResponse>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userAdd(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that enables or disables users.  ## Parameters  - `request`: A JSON object containing the list of users to enable or disable.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Enable users
         * @param {EnableUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userEnable(body: EnableUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UsersResponse>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userEnable(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that updates a user.<br> Normal user can only update themselves, admin can update any user.<br>  ## Parameters  - `request`: A JSON object containing the updated user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Update user
         * @param {UpdateUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userUpdate(body: UpdateUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UsersResponse>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userUpdate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that allows an authenticated admin to retrieve a paginated list of users. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `current`: The current page number.  - `pageSize`: The number of users per page.  - `email`: The email to filter the users by.  - `name`: The name to filter the users by.  ## Returns  If successful, this function returns a `Json<UserList>` object, which includes a success message, the total number of users, and the list of users.  <br> If no users are found, this function returns a `status::NotFound` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if no users are found.  # Example  GET /api/user-list?current=1&pageSize=10&email=test@test.com&name=Test
         * @summary Get the List of Users
         * @param {number} current 
         * @param {number} page_size 
         * @param {string} [email] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async users(current: number, page_size: number, email?: string, name?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserList>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).users(current, page_size, email, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that retrieves all users.  ## Parameters  - `current`: The current page number for pagination. This parameter is currently unused.  - `pageSize`: The number of items per page for pagination. This parameter is currently unused.  - `accessible`: A boolean value indicating whether the user is accessible. This parameter is currently unused.  - `status`: The status of the user. This parameter is currently unused.  ## Returns  If successful, this function returns a `Json<UserList>` object containing the users.
         * @summary Get Users for client
         * @param {number} current 
         * @param {number} page_size 
         * @param {boolean} [accessible] 
         * @param {number} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersClient(current: number, page_size: number, accessible?: boolean, status?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserList>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).usersClient(current, page_size, accessible, status, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This function is an API endpoint that allows an authenticated user to retrieve their current user information. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `request`: The request data, which includes the current user information.  <br>  ## Returns  If successful, this function returns a `Json<CurrentUserResponse>` object, which includes the current user information.  <br> If the user is not authorized, this function returns a `status::Unauthorized` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if the user is not authorized.
         * @summary Get the Current User
         * @param {CurrentUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUser(body: CurrentUserRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<CurrentUserResponse>> {
            return UserApiFp(configuration).currentUser(body, options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that adds a new user.  ## Parameters  - `request`: A JSON object containing the new user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Add user
         * @param {AddUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAdd(body: AddUserRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<UsersResponse>> {
            return UserApiFp(configuration).userAdd(body, options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that enables or disables users.  ## Parameters  - `request`: A JSON object containing the list of users to enable or disable.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Enable users
         * @param {EnableUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userEnable(body: EnableUserRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<UsersResponse>> {
            return UserApiFp(configuration).userEnable(body, options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that updates a user.<br> Normal user can only update themselves, admin can update any user.<br>  ## Parameters  - `request`: A JSON object containing the updated user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
         * @summary Update user
         * @param {UpdateUserRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userUpdate(body: UpdateUserRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<UsersResponse>> {
            return UserApiFp(configuration).userUpdate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that allows an authenticated admin to retrieve a paginated list of users. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `current`: The current page number.  - `pageSize`: The number of users per page.  - `email`: The email to filter the users by.  - `name`: The name to filter the users by.  ## Returns  If successful, this function returns a `Json<UserList>` object, which includes a success message, the total number of users, and the list of users.  <br> If no users are found, this function returns a `status::NotFound` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if no users are found.  # Example  GET /api/user-list?current=1&pageSize=10&email=test@test.com&name=Test
         * @summary Get the List of Users
         * @param {number} current 
         * @param {number} page_size 
         * @param {string} [email] 
         * @param {string} [name] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async users(current: number, page_size: number, email?: string, name?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserList>> {
            return UserApiFp(configuration).users(current, page_size, email, name, options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that retrieves all users.  ## Parameters  - `current`: The current page number for pagination. This parameter is currently unused.  - `pageSize`: The number of items per page for pagination. This parameter is currently unused.  - `accessible`: A boolean value indicating whether the user is accessible. This parameter is currently unused.  - `status`: The status of the user. This parameter is currently unused.  ## Returns  If successful, this function returns a `Json<UserList>` object containing the users.
         * @summary Get Users for client
         * @param {number} current 
         * @param {number} page_size 
         * @param {boolean} [accessible] 
         * @param {number} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersClient(current: number, page_size: number, accessible?: boolean, status?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<UserList>> {
            return UserApiFp(configuration).usersClient(current, page_size, accessible, status, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * This function is an API endpoint that allows an authenticated user to retrieve their current user information. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `request`: The request data, which includes the current user information.  <br>  ## Returns  If successful, this function returns a `Json<CurrentUserResponse>` object, which includes the current user information.  <br> If the user is not authorized, this function returns a `status::Unauthorized` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if the user is not authorized.
     * @summary Get the Current User
     * @param {CurrentUserRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async currentUser(body: CurrentUserRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<CurrentUserResponse>> {
        return UserApiFp(this.configuration).currentUser(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that adds a new user.  ## Parameters  - `request`: A JSON object containing the new user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
     * @summary Add user
     * @param {AddUserRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userAdd(body: AddUserRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<UsersResponse>> {
        return UserApiFp(this.configuration).userAdd(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that enables or disables users.  ## Parameters  - `request`: A JSON object containing the list of users to enable or disable.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
     * @summary Enable users
     * @param {EnableUserRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userEnable(body: EnableUserRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<UsersResponse>> {
        return UserApiFp(this.configuration).userEnable(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that updates a user.<br> Normal user can only update themselves, admin can update any user.<br>  ## Parameters  - `request`: A JSON object containing the updated user information.  ## Returns  If successful, this function returns a `Json<UsersResponse>` object containing the updated user information.
     * @summary Update user
     * @param {UpdateUserRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userUpdate(body: UpdateUserRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<UsersResponse>> {
        return UserApiFp(this.configuration).userUpdate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that allows an authenticated admin to retrieve a paginated list of users. It is tagged with \"user\" for OpenAPI documentation.  ## Parameters  - `current`: The current page number.  - `pageSize`: The number of users per page.  - `email`: The email to filter the users by.  - `name`: The name to filter the users by.  ## Returns  If successful, this function returns a `Json<UserList>` object, which includes a success message, the total number of users, and the list of users.  <br> If no users are found, this function returns a `status::NotFound` error.  <br>  ## Errors  This function will return an error if the system is in maintenance mode, or if no users are found.  # Example  GET /api/user-list?current=1&pageSize=10&email=test@test.com&name=Test
     * @summary Get the List of Users
     * @param {number} current 
     * @param {number} page_size 
     * @param {string} [email] 
     * @param {string} [name] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async users(current: number, page_size: number, email?: string, name?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserList>> {
        return UserApiFp(this.configuration).users(current, page_size, email, name, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that retrieves all users.  ## Parameters  - `current`: The current page number for pagination. This parameter is currently unused.  - `pageSize`: The number of items per page for pagination. This parameter is currently unused.  - `accessible`: A boolean value indicating whether the user is accessible. This parameter is currently unused.  - `status`: The status of the user. This parameter is currently unused.  ## Returns  If successful, this function returns a `Json<UserList>` object containing the users.
     * @summary Get Users for client
     * @param {number} current 
     * @param {number} page_size 
     * @param {boolean} [accessible] 
     * @param {number} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async usersClient(current: number, page_size: number, accessible?: boolean, status?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserList>> {
        return UserApiFp(this.configuration).usersClient(current, page_size, accessible, status, options).then((request) => request(this.axios, this.basePath));
    }
}
