/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AbPeer
 */
export interface AbPeer {

    /**
     * @type {string}
     * @memberof AbPeer
     */
    id: string;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    hash?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    password?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    username?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    hostname?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    platform?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    alias?: string | null;

    /**
     * @type {Array<string>}
     * @memberof AbPeer
     */
    tags?: Array<string> | null;

    /**
     * @type {boolean}
     * @memberof AbPeer
     */
    force_always_relay?: boolean | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    rdp_port?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    rdp_username?: string | null;

    /**
     * @type {string}
     * @memberof AbPeer
     */
    login_name?: string | null;

    /**
     * @type {boolean}
     * @memberof AbPeer
     */
    same_server?: boolean | null;
}
