/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AbProfile } from './ab-profile';
 /**
 * 
 *
 * @export
 * @interface AbSharedProfilesResponse
 */
export interface AbSharedProfilesResponse {

    /**
     * @type {string}
     * @memberof AbSharedProfilesResponse
     */
    error?: string | null;

    /**
     * @type {number}
     * @memberof AbSharedProfilesResponse
     */
    total: number;

    /**
     * @type {Array<AbProfile>}
     * @memberof AbSharedProfilesResponse
     */
    data: Array<AbProfile>;
}
