/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddUserRequest
 */
export interface AddUserRequest {

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    name: string;

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    password: string;

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    confirmPassword: string;

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    email: string;

    /**
     * @type {boolean}
     * @memberof AddUserRequest
     */
    isAdmin: boolean;

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    groupName: string;
}
