/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Group
 */
export interface Group {

    /**
     * @type {string}
     * @memberof Group
     */
    guid: string;

    /**
     * @type {string}
     * @memberof Group
     */
    name: string;

    /**
     * @type {string}
     * @memberof Group
     */
    team: string;

    /**
     * @type {string}
     * @memberof Group
     */
    created_at: string;

    /**
     * @type {Array<string>}
     * @memberof Group
     */
    access_to: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof Group
     */
    accessed_from: Array<string>;

    /**
     * @type {string}
     * @memberof Group
     */
    note?: string | null;

    /**
     * @type {string}
     * @memberof Group
     */
    info: string;
}
