/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HeartbeatRequest
 */
export interface HeartbeatRequest {

    /**
     * @type {string}
     * @memberof HeartbeatRequest
     */
    id: string;

    /**
     * @type {number}
     * @memberof HeartbeatRequest
     */
    modified_at: number;

    /**
     * @type {string}
     * @memberof HeartbeatRequest
     */
    uuid: string;

    /**
     * @type {number}
     * @memberof HeartbeatRequest
     */
    ver: number;
}
