/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Token } from './token';
import { UserInfo } from './user-info';
 /**
 * 
 *
 * @export
 * @interface LoginReply
 */
export interface LoginReply {

    /**
     * @type {string}
     * @memberof LoginReply
     */
    type: string;

    /**
     * @type {UserInfo}
     * @memberof LoginReply
     */
    user: UserInfo;

    /**
     * @type {Token}
     * @memberof LoginReply
     */
    access_token: Token;
}
