/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OidcUser } from './oidc-user';
 /**
 * 
 *
 * @export
 * @interface OidcResponse
 */
export interface OidcResponse {

    /**
     * @type {string}
     * @memberof OidcResponse
     */
    accessToken: string;

    /**
     * @type {string}
     * @memberof OidcResponse
     */
    type: string;

    /**
     * @type {string}
     * @memberof OidcResponse
     */
    tfaType: string;

    /**
     * @type {string}
     * @memberof OidcResponse
     */
    secret: string;

    /**
     * @type {OidcUser}
     * @memberof OidcResponse
     */
    user: OidcUser;
}
