/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OidcUserInfo } from './oidc-user-info';
 /**
 * 
 *
 * @export
 * @interface OidcUser
 */
export interface OidcUser {

    /**
     * @type {string}
     * @memberof OidcUser
     */
    name: string;

    /**
     * @type {string}
     * @memberof OidcUser
     */
    email: string;

    /**
     * @type {string}
     * @memberof OidcUser
     */
    note: string;

    /**
     * @type {number}
     * @memberof OidcUser
     */
    status: number;

    /**
     * @type {OidcUserInfo}
     * @memberof OidcUser
     */
    info: OidcUserInfo;

    /**
     * @type {boolean}
     * @memberof OidcUser
     */
    isAdmin: boolean;

    /**
     * @type {string}
     * @memberof OidcUser
     */
    thirdAuthType: string;
}
