/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OidcDeviceInfo } from './oidc-device-info';
 /**
 * 
 *
 * @export
 * @interface OidcAuthRequest
 */
export interface OidcAuthRequest {

    /**
     * @type {OidcDeviceInfo}
     * @memberof OidcAuthRequest
     */
    deviceInfo: OidcDeviceInfo;

    /**
     * @type {string}
     * @memberof OidcAuthRequest
     */
    id: string;

    /**
     * @type {string}
     * @memberof OidcAuthRequest
     */
    op: string;

    /**
     * @type {string}
     * @memberof OidcAuthRequest
     */
    uuid: string;
}
