/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PeerInfo } from './peer-info';
 /**
 * 
 *
 * @export
 * @interface Peer
 */
export interface Peer {

    /**
     * @type {string}
     * @memberof Peer
     */
    guid: string;

    /**
     * @type {string}
     * @memberof Peer
     */
    id: string;

    /**
     * @type {number}
     * @memberof Peer
     */
    status: number;

    /**
     * @type {string}
     * @memberof Peer
     */
    strategyName: string;

    /**
     * @type {string}
     * @memberof Peer
     */
    last_online: string;

    /**
     * @type {PeerInfo}
     * @memberof Peer
     */
    info: PeerInfo;
}
