/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PeerInfo
 */
export interface PeerInfo {

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    cpu?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    hostname?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    memory?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    os?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    username?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    uuid?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    version?: string | null;

    /**
     * @type {string}
     * @memberof PeerInfo
     */
    ip?: string | null;
}
