/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Peer } from './peer';
 /**
 * 
 *
 * @export
 * @interface PeersResponse
 */
export interface PeersResponse {

    /**
     * @type {string}
     * @memberof PeersResponse
     */
    msg: string;

    /**
     * @type {number}
     * @memberof PeersResponse
     */
    total: number;

    /**
     * @type {Array<Peer>}
     * @memberof PeersResponse
     */
    data: Array<Peer>;
}
