/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Provider
 */
export interface Provider {

    /**
     * @type {string}
     * @memberof Provider
     */
    name: string;

    /**
     * @type {number}
     * @memberof Provider
     */
    orderIndex: number;

    /**
     * @type {boolean}
     * @memberof Provider
     */
    enabled: boolean;

    /**
     * @type {string}
     * @memberof Provider
     */
    clientId: string;

    /**
     * @type {string}
     * @memberof Provider
     */
    clientSecret: string;

    /**
     * @type {string}
     * @memberof Provider
     */
    authorizationEndpoint: string;

    /**
     * @type {string}
     * @memberof Provider
     */
    tokenEndpoint: string;

    /**
     * @type {string}
     * @memberof Provider
     */
    userinfoEndpoint: string;
}
