/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateGoupRequest
 */
export interface UpdateGoupRequest {

    /**
     * @type {string}
     * @memberof UpdateGoupRequest
     */
    guid: string;

    /**
     * @type {string}
     * @memberof UpdateGoupRequest
     */
    name: string;

    /**
     * @type {string}
     * @memberof UpdateGoupRequest
     */
    note: string;

    /**
     * @type {Array<string>}
     * @memberof UpdateGoupRequest
     */
    allowed_outgoings: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof UpdateGoupRequest
     */
    allowed_incomings: Array<string>;
}
