/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    password?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    confirmPassword?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    email?: string | null;

    /**
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    isAdmin?: boolean | null;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    groupName?: string | null;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    note?: string | null;

    /**
     * @type {number}
     * @memberof UpdateUserRequest
     */
    status?: number | null;
}
