/* tslint:disable */
/* eslint-disable */
/**
 * sctgdesk-api-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserListResponse } from './user-list-response';
 /**
 * 
 *
 * @export
 * @interface UserList
 */
export interface UserList {

    /**
     * @type {string}
     * @memberof UserList
     */
    msg: string;

    /**
     * @type {number}
     * @memberof UserList
     */
    total: number;

    /**
     * @type {Array<UserListResponse>}
     * @memberof UserList
     */
    data: Array<UserListResponse>;
}
